In [1]:
import numpy as np
import pandas as pd

## Datatypes and Attributes

In [2]:
# Numpy's main datatype is ndarray->n dimensional array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
             [4,5.0,6.5]])

a3 = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape


(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
#Checking dimensions
a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

In [13]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
#Total elements in ndarrays
a1.size,a2.size,a3.size

(3, 6, 18)

In [15]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
#Creating a dataframe from a numpy array


print("The a2 ndarray is :", a2)
print("\nThe dataframe from a2 array")

df = pd.DataFrame(a2)
df

The a2 ndarray is : [[1.  2.  3.3]
 [4.  5.  6.5]]

The dataframe from a2 array


0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [18]:
#Created sample a22 array and made a dataframe
a22 = np.array([[23.4,56.1,34.5],
              [45,90,2]])
print(a22)

df2 = pd.DataFrame(a22)
df2


[[23.4 56.1 34.5]
 [45.  90.   2. ]]


0     1     2
0  23.4  56.1  34.5
1  45.0  90.0   2.0

## Creating Arrays


In [19]:
sample_arrays = np.array([1,2,3])
sample_arrays

array([1, 2, 3])

In [20]:
sample_arrays.dtype

dtype('int32')

In [21]:
#Creating arrays of ones using .ones() in numpy filled with ones
ones = np.ones((2,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
#Zeros array
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#Defining array with range
range_array = np.arange(0,10,2)    #low,high,step
range_array

array([0, 2, 4, 6, 8])

In [24]:
#Dafining array with random
random_array = np.random.randint(0,10,size=(3,5))   #low,max,size(3,5)
random_array

array([[4, 1, 0, 3, 6],
       [4, 1, 3, 7, 9],
       [5, 9, 4, 6, 0]])

In [25]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.16071331, 0.98810332, 0.07891315],
       [0.48020389, 0.54944492, 0.12493189],
       [0.54386651, 0.65037809, 0.62036067],
       [0.0906943 , 0.70053889, 0.02963811],
       [0.96946463, 0.71494541, 0.67697566]])

In [26]:
random_array2.shape

(5, 3)

In [27]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.67874522, 0.75348577, 0.81256712],
       [0.27427569, 0.83866278, 0.04238616],
       [0.91477686, 0.45486179, 0.9035132 ],
       [0.52984903, 0.20702291, 0.25121146],
       [0.33403376, 0.92602157, 0.49819432]])

In [28]:
random_array4 = np.random.randint(1,100,size=(5,5))
random_array4

array([[86, 23, 22, 74, 96],
       [46, 42, 72, 29, 82],
       [57,  4, 44, 86,  7],
       [24, 10, 85, 38, 24],
       [32, 40, 58, 76, 12]])

In [29]:
#Pseudo-random numbers
np.random.seed(0)   #this will keep the random numbers changing each time it's executed.
#in seed() any nuber can be given

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
#whenever run without seed, it's automatically changed.
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [31]:
random_array_5 = np.random.random((5,3))
random_array_5


array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Matrices

In [35]:
np.unique(a3) #finding unique elements in an array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [36]:
a1


array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3[:2, :2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [46]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0]],

        [[0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3]],

        [[9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5]]],


       [[[2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6]],

        [[4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4]],

        [[0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2]]]])

In [52]:
a4[:,:,:,:2]

array([[[[1, 1],
         [0, 4],
         [4, 9],
         [1, 0]],

        [[0, 9],
         [5, 5],
         [8, 4],
         [0, 7]],

        [[9, 8],
         [0, 1],
         [0, 1],
         [4, 1]]],


       [[[2, 4],
         [2, 8],
         [6, 2],
         [5, 5]],

        [[4, 6],
         [7, 0],
         [7, 7],
         [6, 1]],

        [[0, 3],
         [0, 4],
         [4, 8],
         [5, 3]]]])

## Manipulating and comparing arrays

### Arithmetic

In [54]:
a1

array([1, 2, 3])

In [56]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [58]:
a1+ones

array([2., 3., 4.])

In [59]:
a1 - ones

array([0., 1., 2.])

In [60]:
a1 * ones

array([1., 2., 3.])

In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [64]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [67]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [70]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [71]:
 a1 % 2

array([1, 0, 1], dtype=int32)

In [72]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [73]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Aggregation

In [74]:
listy = [1,2,3]
type(listy)

list

In [75]:
sum(listy)

6

In [76]:
a1

array([1, 2, 3])

In [77]:
np.sum(a1)

6

In [ ]:
a34 = np.random.random((55295,26989))
np.sum(a34)